services:
  - type: web
    name: creatix-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE}?sslmode=require
      - key: SQL_HOST
        fromDatabase:
          name: creatix-db
          property: host
      - key: SQL_PORT
        fromDatabase:
          name: creatix-db
          property: port
      - key: SQL_DATABASE
        fromDatabase:
          name: creatix-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: creatix-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: creatix-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app # Change this to your Vercel URL
      - key: ADMIN_EMAIL
        value: admin@creatix.com

databases:
  - name: creatix-db
    databaseName: creatix
    user: creatix_user
    plan: free
